# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_text',
            field=models.TextField(default=''),
        ),
    ]
