# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_article_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title_word',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
