# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170304_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField(default='')),
                ('pub_date', models.DateTimeField(verbose_name='note published')),
            ],
        ),
    ]
