# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-31 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about',
            new_name='about_text',
        ),
    ]
